### ISSUE TITLE
Add missing gamemodes to configuration

### ISSUE THREAD

**Issue by McJeffr** [Shotbow/ChatBot#118]
The following gamemodes are not yet on the configuration properly:
- Miner Problems
- Wasted
- Warband

They need to be added in the aliases, names, rooms and forums categories.

**Comment by McJeffr** [comment]
Additionally, it seems like the in-production configuration and the one stored on GitHub are out of sync. There is no support configuration called "spamdm" in the configs, but there is one in production.

**Comment by navarr** [comment]
Configuration is allowed to be out-of-sync.  !spamdm was spun up quickly, not as a new feature of a bot, but just configuring an existing feature for a specific use-case.
