### ISSUE TITLE
As a moderator, I would like to see all deleted messages

### ISSUE THREAD

**Issue by navarr** [Shotbow/ChatBot#45]
New configuration option: channel ID to send messages that have been deleted.

On message deletion, output who the poster was, what the message was, and who deleted it to the configured channel.

**Comment by JamsheedMistri** [comment]
@navarr there's no way to determine who deleted the message, but I can do everything else. Do you still want the feature?

**Comment by navarr** [comment]
@JamsheedMistri Yes please
