### ISSUE TITLE
Suggestion: when a person pings x amount of staff members in a certain timespan, they should be automatically muted

### ISSUE THREAD

**Issue by McJeffr** [Shotbow/ChatBot#62]
As the title says. Might help with people constantly pinging all staff members if they need help because they think that's a good idea.

**Comment by navarr** [comment]
This would definitely be reactionary to someone currently pinging all staff.  This person already has broken the rules and probably doesn't care.

What _might_ be cool is if the bot could detect who is being pinged (someone with the staff role) and after 2 pings of staff from the same person within a quick timespan (or a single message with more than 2 staff pings) they are temporarily muted with a one minute cooldown and a message (that automatically deletes itself after a minute) is posted in the chatroom explaining not to ping staff members

**Comment by McJeffr** [comment]
Sounds like a better idea indeed
