### ISSUE TITLE
Update discord.js to version 12

### ISSUE THREAD

**Issue by McJeffr** [Shotbow/ChatBot#69]
Discord is changing their domain from discordapp.com to discord.com. They will do this on November 7th, we must ensure that we have updated Discord.js prior to that date otherwise it will stop working.

Discord.js have already updated the domains, but have yet to roll a release of these changes. As soon as they do, we should update to the latest version of Discord.js.

**Comment by pedrofracassi** [comment]
Meanwhile, you can pass an options object to the client, and change HTTP settings to match the new domain: https://discord.js.org/#/docs/main/v11/typedef/ClientOptions

**Comment by McJeffr** [comment]
We will need to update to discord.js v12. This change from 11 to 12 has introduced some breaking changes after some initial tests, most of them are documented here: https://discordjs.guide/additional-info/changes-in-v12.html#before-you-start.
