### ISSUE TITLE
Bug: muted users can still execute commands, though their command message is deleted

### ISSUE THREAD

**Issue by McJeffr** [Shotbow/ChatBot#73]
Reproduction steps:

1. Mute yourself / another user
2. Execute any command / let a muted user execute any command
3. ChatBot responds to the command and executes the command
4. ChatBot sees that you / another user is muted and deletes your message

The reply of ChatBot is still in the channel. This means that you can indirectly spam a channel by spamming commands, even though you are muted.

**Comment by navarr** [comment]
This is not a major issue.  For the most part, channels permissions are set such that a muted person cannot send messages to the channel through Discord's RBAC.

Adding the functionality of mute deleting messages was due to unintentional? abuse by Nitro boosters in the nitro channel.

**Comment by McJeffr** [comment]
Possibly, I think it was also not a thing back in the day with permissions like that. But I just noticed it on my development server, which obviously isn't a perfect copy of Shotbow's server so the issue might have looked more severe than it actually was. Either way, it's a quick fix in the main command handler probably by just adding a role check.

**Comment by JamsheedMistri** [comment]
I agree, this would be a simple fix to check if they have the muted role in the command handler.
