### ISSUE TITLE
Feature: Overhauled presence using Rich Presence

### ISSUE THREAD

**Issue by McJeffr** [Shotbow/ChatBot#77]
Back when we wrote the initial version of the "Playing on Shotbow with x others", the Rich Presence API didn't really exist yet. Nowadays, we do have it, luckily!

We should look at implementing the Rich Presence API nicely for Chat Bot. This means displaying the current information about the amount of players online, but also maybe something like the server IP or website. Though Rich Presence is mainly for games, and there is an SDK for Discord, we don't necessarily need this. IDEs such as IntelliJ or VS Code also implement it.

More information here: https://discord.com/developers/docs/rich-presence/how-to and on the Application page for Chat Bot.

**Comment by navarr** [comment]
Rich Presence isn't supported for bots.

**Comment by McJeffr** [comment]
Oh, I wasn't aware that bots didn't support it. Alright, that will make this impossible yeah.
