### ISSUE TITLE
Decrease size of Docker Image

### ISSUE THREAD

**Issue by navarr** [Shotbow/ChatBot#88]
https://medium.com/trendyol-tech/how-we-reduce-node-docker-image-size-in-3-steps-ff2762b51d5a

**Comment by McJeffr** [comment]
In addition to optimizing the size of the Dockerfile, we can use Caching within Github Actions to cache our npm dependencies. This could speed up the slowest step of all, which is `npm install --production`. https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

**Comment by navarr** [comment]
Yes!  We can probably also use Caching within Github Actions to cache the docker images we depend on, which would speed up builds too.
